services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    user: root
    group_add:
      - "${DOCKER_GROUP_ID:-984}"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "127.0.0.1:9273:9273"
    networks:
      - dmas-network
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - dmas-network
    restart: unless-stopped

networks:
  dmas-network:
    external: true
volumes:
  prometheus-data:
