global:
  scrape_interval: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']
        labels:
          instance: 'docker-metrics'
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'openai-proxy'
    static_configs:
      - targets: ['openai-proxy:8001']
  
  - job_name: 'ollama-proxy'
    static_configs:
      - targets: ['ollama-proxy:8003']