global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'openai-proxy'
    static_configs:
      - targets: ['openai-proxy:8001']

  - job_name: 'ollama-proxy'
    static_configs:
      - targets: ['ollama-proxy:8003']